name       : antibody
version    : 3.6.1
release    : 1
source     :
    - https://github.com/getantibody/antibody/archive/v3.6.1.tar.gz : 5971c251c43375ea5de9334cdbb1e4a1da500e03ecd63372c1c11f68f0364fe2
license    : MIT
component  : system.utils
summary    : A fast zsh plugin manager
description: |
    Antibody is a shell plugin manager made from the ground up thinking about performance.
extract    : no
networking : yes
builddeps  :
    - dep
    - git
    - golang
setup      : |
    mkdir -p $(go env GOPATH)/src/github.com/getantibody/antibody
    tar xf $sources/v${version}.tar.gz -C $(go env GOPATH)/src/github.com/getantibody/antibody --strip-components 1
    cd $(go env GOPATH)/src/github.com/getantibody/antibody
    dep ensure -vendor-only
build      : |
    cd $(go env GOPATH)/src/github.com/getantibody/antibody
    %make build
install    : |
    cd $(go env GOPATH)/src/github.com/getantibody/antibody
    install -Dm00755 ./antibody $installdir/usr/bin/antibody
check      : |
    cd $(go env GOPATH)/src/github.com/getantibody/antibody
    %make test
