name       : antibody
version    : 4.0.1
release    : 2
source     :
    - https://github.com/getantibody/antibody/archive/v4.0.1.tar.gz : 644a2217c444731f4a438a2ca2bb3e3179c13934139bc14abb5ddbd65a08b20a
license    : MIT
component  : system.utils
summary    : A fast zsh plugin manager
description: |
    Antibody is a shell plugin manager made from the ground up thinking about performance.
extract    : no
networking : yes
builddeps  :
    - dep
    - git
    - golang
environment: |
    antibody_path=$(go env GOPATH)/src/github.com/getantibody/antibody
setup      : |
    mkdir -p $antibody_path
    tar xf $sources/v${version}.tar.gz -C $antibody_path --strip-components 1
    cd $antibody_path
    dep ensure -vendor-only
build      : |
    cd $antibody_path
    %make build
install    : |
    install -Dm00755 $antibody_path/antibody $installdir/usr/bin/antibody
check      : |
    cd $antibody_path
    %make test
