name       : antibody
version    : 4.1.2
release    : 5
source     :
    - https://github.com/getantibody/antibody/archive/v4.1.2.tar.gz : 79e857c79cf51bff0bf42ef970a31341445911dc19cf24efb8faa01584855905
license    : MIT
component  : system.utils
summary    : A fast zsh plugin manager
description: |
    Antibody is a shell plugin manager made from the ground up thinking about performance.
networking : yes
builddeps  :
    - git
    - golang
build      : |
    %make
install    : |
    install -Dm00755 antibody $installdir/usr/bin/antibody
check      : |
    %make test
