name       : antibody
version    : 6.1.0
release    : 8
source     :
    - https://github.com/getantibody/antibody/archive/v6.1.0.tar.gz : b2cf67af801ebf10c0d52b1767cbdb5e3ab5a1713e6c3d28616a109e1d7906a7
license    : MIT
component  : system.utils
summary    : A fast zsh plugin manager
description: |
    Antibody is a shell plugin manager made from the ground up thinking about performance.
networking : yes
builddeps  :
    - git
    - golang
build      : |
    %make
install    : |
    install -Dm00755 antibody $installdir/usr/bin/antibody
check      : |
    %make test
