name       : antibody
version    : 4.1.0
release    : 3
source     :
    - https://github.com/getantibody/antibody/archive/v4.1.0.tar.gz : aac40071846c09febccac3e540ce4cd3855868972bcea6a9aa903ab8bfa5ff4d
license    : MIT
component  : system.utils
summary    : A fast zsh plugin manager
description: |
    Antibody is a shell plugin manager made from the ground up thinking about performance.
networking : yes
builddeps  :
    - git
    - golang
build      : |
    %make
install    : |
    install -Dm00755 antibody $installdir/usr/bin/antibody
check      : |
    %make test
