name       : antibody
version    : 6.0.0
release    : 7
source     :
    - https://github.com/getantibody/antibody/archive/v6.0.0.tar.gz : 40dbe2ff67117e63a8c98290c7a80f72e0cbd9cff2473a8b6d0eef45bd205443
license    : MIT
component  : system.utils
summary    : A fast zsh plugin manager
description: |
    Antibody is a shell plugin manager made from the ground up thinking about performance.
networking : yes
builddeps  :
    - git
    - golang
build      : |
    %make
install    : |
    install -Dm00755 antibody $installdir/usr/bin/antibody
check      : |
    %make test
